import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/src/components/ui/sonner";
import { ThemeProvider } from "@/src/components/ui/theme-provider";
// import Header from "@/src/components/ui/header";
import { cn } from "@/lib/utils";
import { ReserveProvider } from "@/context/ReserveContext";
// import Footer from "@/src/components/ui/footer";
// import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
      {/* <Link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Geist+Mono&display=swap"
        /> */}
      </head>
      <body
        className={cn(
          "font-sans",
          geistSans.variable,
          geistMono.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReserveProvider>
            {/* <Header /> */}
            {children}
            <Toaster />
            {/* <Footer/> */}
          </ReserveProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
